// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package xratedelivery

import (
	"github.com/tiagohora/test-app/src/subject/xrate/data"
	"github.com/tiagohora/test-app/src/subject/xrate/domain/service"
)

// Injectors from factory.go:

func Factory() ExchangeRateConsumer {
	repositoryInterface := data.New()
	exchangeRateService := service.New(repositoryInterface)
	xratedeliveryExchangeRateConsumer := New(exchangeRateService)
	return xratedeliveryExchangeRateConsumer
}
